[package]
name = "s0ra-sshd"
version = "0.1.0"
edition = "2024"

[dependencies]
portable-pty = "0.9.0"
rustls-pemfile = "2.2.0"
tokio = { version = "1.49.0", features = ["full"] }
tokio-rustls = "0.26.4"
