[package]
name = "ssh0-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
libssh0 = {path = "../utility-lib"}
dirs = "6.0.0"
portable-pty = "0.9.0"
rcgen = "0.14.7"
rustls-pemfile = "2.2.0"
tokio = { version = "1.49.0", features = ["full"] }
tokio-rustls = "0.26.4"
